# Generated by Django 4.0.5 on 2022-06-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phots',
            new_name='Photos',
        ),
        migrations.AlterModelTable(
            name='photos',
            table='photos',
        ),
    ]
