# Generated by Django 3.1.7 on 2021-10-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(verbose_name='日時')),
                ('guest', models.CharField(max_length=10, verbose_name='ゲスト')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
                ('furi', models.CharField(max_length=50, verbose_name='ふりがな')),
                ('tel', models.CharField(max_length=13, verbose_name='電話番号')),
                ('mail', models.EmailField(max_length=100, verbose_name='メールアドレス')),
                ('post', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=100, verbose_name='住所')),
                ('message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='メッセージ')),
                ('allergy', models.CharField(blank=True, max_length=500, null=True, verbose_name='アレルギー')),
                ('conpanion1', models.CharField(blank=True, max_length=50, null=True, verbose_name='お連れ様１')),
                ('conpanion2', models.CharField(blank=True, max_length=50, null=True, verbose_name='お連れ様２')),
                ('conpanion3', models.CharField(blank=True, max_length=50, null=True, verbose_name='お連れ様３')),
                ('attendance', models.CharField(max_length=10, verbose_name='出欠')),
            ],
            options={
                'db_table': 'rsvp',
            },
        ),
    ]
