# Generated by Django 3.1.7 on 2021-10-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_auto_20211028_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='bus',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='送迎バス'),
        ),
    ]
